name: Pull-Requests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradle assemble
        run: ./gradlew assemble
        env:
          TOKEN: ${{ secrets.AUTO_TOKEN }}
          USERNAME: ${{ secrets.AUTO_USERNAME }}

      - name: Run Tests
        run: ./gradlew testDebugUnitTest
