name: Publish

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradle assemble
        run: ./gradlew assemble

#      - name: Run Tests
#        run: ./gradlew testDebugUnitTest

      - name: Publish
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
