name: Publish

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradle assemble
        run: ./gradlew assemble

#      - name: Run Tests
#        run: ./gradlew testDebugUnitTest

      - name: Publish
        run: ./gradlew publish
        env:
          sonatypeUsernameEnv: ${{ secrets.SONATYPEUSERNAME }}
          sonatypePasswordEnv: ${{ secrets.SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASS }}

